### ISSUE TITLE
[Feature req] Convolutions of dependent random vectors. 

### ISSUE THREAD

**Issue by rand5** [lrnv/Copulas.jl#240]
I'm migrating a problem discussed [here](https://discourse.julialang.org/t/convolution-of-dependent-random-variables-with-copula/124603) that involves computing the convolution of two dependent random variables where their joint distribution is defined by a copula. I believe the issue may stem from the fact that evaluating the pdf of the copula sometimes returns NaN when it should return 0. 
Here is an example with marginal distributions that should have support over all reals:
```
X1 = Gumbel(15.,5.)
X2 = MixtureModel([Normal(-6.,0.1),X1],[0.9,0.1])

ρ = 0.4

C = GaussianCopula([1. ρ; ρ 1.])

D1 = SklarDist(C,(X1,X2))

pdf(D1,[-30., -30.]) #Returns NaN
```

The link above has an attempt at a brute force work-around, but it doesn't seem to be sufficient (see the plot in the link).

**Comment by lrnv** [comment]
Looks indeed like a bug, or rather a missed special case somewhere. By the way: 

```
julia> pdf(D1,big.([-30., -30.])) #Returns NaN
9.800107565129330824766557211886842343262822051986735333987174617133175015382767e-5024

julia>
```

so yes, should definitely return 0. Let me take a look as soon as i have a moment.

**Comment by lrnv** [comment]
The right patch would be to add a `pdf(C::GaussianCopula,...)` method as for the moment there is none. We could do it directly at the `C::EllipticalCopula` level. Its not too hard to do based on the existing `cdf(C::EllipticalCopula,...)` implementation.

**Comment by rand5** [comment]
I tried a few other copulas (Clayton, Gumbel, Joe) and am getting similar domain errors. Would this need to be addressed for `C::ArchimedeanCopula` as well?

**Comment by lrnv** [comment]
At the same [0,0] point of evaluation ? Yes then there is another bug in the archimedean pdf algorithm

**Comment by lrnv** [comment]
Hum... Taking another look at the gaussian case, the NaN actually comes from `Distributions.jl` : 

```
julia> pdf(MvNormal(C.Σ),[-Inf,-Inf])
NaN

julia>
```

**Comment by rand5** [comment]
Here is what I was using to check the Archimedian Copulas
```
X1 = Normal()


d = 2
θ = 1.

Cs = [ClaytonCopula(d,θ), FrankCopula(d,θ), GumbelCopula(d,θ), JoeCopula(d,θ)] #Copulas to check. Make sure θ is appropriate

for k=1:length(Cs)
    D1 = SklarDist(Cs[k],(X1,X1))

    N = 100
    Zs = collect(range(-10.,10.,N))
    ConvD = map(Zs) do z
        quadgk(x->pdf(D1,[x,z-x]), -100., 100., rtol=1e-6)[1]
    end
end
```

It is not clear to me at which point the NaN is being produced since 
```
X1 = Normal()

d = 2
θ = 1.

C = ClaytonCopula(d,θ)

 D1 = SklarDist(C,(X1,X1))

N = 100
Zs = collect(range(-10.,10.,N))
ConvD = map(Zs) do z
    quadgk(x->pdf(D1,[x,z-x]), -100., 100., rtol=1e-6)[1]
end
```
gives 
```
DomainError with 0.0:
integrand produced NaN in the interval (-100.0, 100.0)

Stacktrace:
  [1] evalrule(f::var"#87#89"{Float64}, a::Float64, b::Float64, x::Vector{Float64}, w::Vector{Float64}, wg::Vector{Float64}, nrm::typeof(norm))
    @ QuadGK C:\Users\Monali\.julia\packages\QuadGK\BjmU0\src\evalrule.jl:39
  [2] #8
    @ C:\Users\Monali\.julia\packages\QuadGK\BjmU0\src\adapt.jl:54 [inlined]
  [3] ntuple
    @ .\ntuple.jl:48 [inlined]
  [4] do_quadgk(f::var"#87#89"{Float64}, s::Tuple{Float64, Float64}, n::Int64, atol::Nothing, rtol::Float64, maxevals::Int64, nrm::typeof(norm), _segbuf::Nothing, eval_segbuf::Nothing)
    @ QuadGK C:\Users\Monali\.julia\packages\QuadGK\BjmU0\src\adapt.jl:52
  [5] #50
    @ C:\Users\Monali\.julia\packages\QuadGK\BjmU0\src\api.jl:83 [inlined]
  [6] handle_infinities(workfunc::QuadGK.var"#50#51"{Nothing, Float64, Int64, Int64, typeof(norm), Nothing, Nothing}, f::var"#87#89"{Float64}, s::Tuple{Float64, Float64})
    @ QuadGK C:\Users\Monali\.julia\packages\QuadGK\BjmU0\src\adapt.jl:189
  [7] #quadgk#49
    @ C:\Users\Monali\.julia\packages\QuadGK\BjmU0\src\api.jl:82 [inlined]
  [8] quadgk
    @ C:\Users\Monali\.julia\packages\QuadGK\BjmU0\src\api.jl:80 [inlined]
  [9] #86
    @ .\In[152]:14 [inlined]
 [10] iterate
    @ .\generator.jl:47 [inlined]
 [11] _collect(c::Vector{Float64}, itr::Base.Generator{Vector{Float64}, var"#86#88"}, ::Base.EltypeUnknown, isz::Base.HasShape{1})
    @ Base .\array.jl:854
 [12] collect_similar(cont::Vector{Float64}, itr::Base.Generator{Vector{Float64}, var"#86#88"})
    @ Base .\array.jl:763
 [13] map(f::Function, A::Vector{Float64})
    @ Base .\abstractarray.jl:3285
 [14] top-level scope
    @ In[152]:13
```
but 
```
pdf(D1,[0.,0.]) # not NaN
```

**Comment by lrnv** [comment]
Okay so let's split up.

For the Gaussian, i reported upstream there : https://github.com/JuliaStats/Distributions.jl/issues/1937

For the archimedeans, I'll come back when I know more

**Comment by lrnv** [comment]
@rand5 The archimedean ones shoul dbe fixed in the currently registrating 0.1.27 version of the copulas package. On it, I have : 

```julia
using Copulas, Distributions, QuadGK
X1 = Normal()


d = 2
θ = 1.

Cs = [
    ClaytonCopula(d,θ), 
    FrankCopula(d,θ), 
    GumbelCopula(d,θ), 
    JoeCopula(d,θ)
] #Copulas to check. Make sure θ is appropriate

N = 100
Zs = collect(range(-10.,10.,N))
ConvDs = zeros(length(Cs), length(Zs))
for k=1:length(Cs)
    D1 = SklarDist(Cs[k],(X1,X1))
    ConvDs[k,:] = map(Zs) do z
        quadgk(x->pdf(D1,[x,z-x]), -100., 100., rtol=1e-6)[1]
    end
end

p = plot()
for k in 1:length(Cs)
    plot!(p, Zs, ConvDs[k,:], label=k)
end
p

```

producing the folloiwng densities: 

![plot_6](https://github.com/user-attachments/assets/a165d202-ccd8-4a9c-9ac7-e754507247ca)


However, the Gaussian one is not fixed yet because the issues comes from Distributions.jl (and potentially form PDMats.jl directly), will take a bit more time as it is not up to me alone. :/

**Comment by rand5** [comment]
@lrnv I'm using v0.1.27 and still getting domain errors:
```
X1 = Gumbel(15.,5.)
X2 = MixtureModel([Normal(-6.,0.1),X1],[0.9,0.1])

θ = 2.5
d= 2
C = GumbelCopula(d,θ)

D1 = SklarDist(C,(X1,X2))

N = 100
Zs = collect(range(-10.,10.,N))
ConvD = map(Zs) do z
    quadgk(x->pdf(D1,[x,z-x]), -100., 100., rtol=1e-6)[1]
end
```
which throws:
```
DomainError with 0.0:
integrand produced NaN in the interval (-100.0, 100.0)

Stacktrace:
  [1] evalrule(f::var"#2#4"{Float64}, a::Float64, b::Float64, x::Vector{Float64}, w::Vector{Float64}, wg::Vector{Float64}, nrm::typeof(norm))
    @ QuadGK C:\Users\Monali\.julia\packages\QuadGK\BjmU0\src\evalrule.jl:39
  [2] #8
    @ C:\Users\Monali\.julia\packages\QuadGK\BjmU0\src\adapt.jl:54 [inlined]
  [3] ntuple
    @ .\ntuple.jl:48 [inlined]
  [4] do_quadgk(f::var"#2#4"{Float64}, s::Tuple{Float64, Float64}, n::Int64, atol::Nothing, rtol::Float64, maxevals::Int64, nrm::typeof(norm), _segbuf::Nothing, eval_segbuf::Nothing)
    @ QuadGK C:\Users\Monali\.julia\packages\QuadGK\BjmU0\src\adapt.jl:52
  [5] #50
    @ C:\Users\Monali\.julia\packages\QuadGK\BjmU0\src\api.jl:83 [inlined]
  [6] handle_infinities(workfunc::QuadGK.var"#50#51"{Nothing, Float64, Int64, Int64, typeof(norm), Nothing, Nothing}, f::var"#2#4"{Float64}, s::Tuple{Float64, Float64})
    @ QuadGK C:\Users\Monali\.julia\packages\QuadGK\BjmU0\src\adapt.jl:189
  [7] #quadgk#49
    @ C:\Users\Monali\.julia\packages\QuadGK\BjmU0\src\api.jl:82 [inlined]
  [8] quadgk
    @ C:\Users\Monali\.julia\packages\QuadGK\BjmU0\src\api.jl:80 [inlined]
  [9] #1
    @ .\In[3]:4 [inlined]
 [10] iterate
    @ .\generator.jl:47 [inlined]
 [11] _collect(c::Vector{Float64}, itr::Base.Generator{Vector{Float64}, var"#1#3"}, ::Base.EltypeUnknown, isz::Base.HasShape{1})
    @ Base .\array.jl:854
 [12] collect_similar(cont::Vector{Float64}, itr::Base.Generator{Vector{Float64}, var"#1#3"})
    @ Base .\array.jl:763
 [13] map(f::Function, A::Vector{Float64})
    @ Base .\abstractarray.jl:3285
 [14] top-level scope
    @ In[3]:3
```

**Comment by rand5** [comment]
```
pdf(D1,[-100.,100.]) # = NaN
```

**Comment by lrnv** [comment]
@rand5 using this we can see what is happening:

```julia
using Copulas, Distributions, QuadGK
X1 = Gumbel(15.,5.)
X2 = MixtureModel([Normal(-6.,0.1),X1],[0.9,0.1])

θ = 2.5
d= 2
C = GumbelCopula(d,θ)

D1 = SklarDist(C,(X1,X2))

N = 100
Zs = collect(range(-10.,10.,N))
function verbose_pdf(D,x)
    u = cdf.(D.m, x)
    @show u, pdf(D.C, u), pdf.(D.m, x)
    return pdf(D, x)
end
ConvD = map(Zs) do z
    quadgk(x->verbose_pdf(D1,[x,z-x]), -100., 100., rtol=1e-6)[1]
end
```

yields: 

```julia
(u, pdf(D.C, u), pdf.(D.m, x)) = ([1.8921786948382924e-9, 3.5073891964646353e-66], 1.7443112753073484e7, [7.601085008088713e-9, 1.0410854216991285e-64])
(u, pdf(D.C, u), pdf.(D.m, x)) = ([0.0, 0.9097651438198867], NaN, [0.0, 0.004543430210439768])
(u, pdf(D.C, u), pdf.(D.m, x)) = ([0.7299075788991536, 0.0], NaN, [0.045960434613928486, 0.0])
(u, pdf(D.C, u), pdf.(D.m, x)) = ([0.0, 0.9999999153502569], NaN, [0.0, 1.692994145650427e-8])
(u, pdf(D.C, u), pdf.(D.m, x)) = ([0.9999998854389884, 0.0], NaN, [2.291220099222903e-8, 0.0])
(u, pdf(D.C, u), pdf.(D.m, x)) = ([0.0, 0.999999963708878], NaN, [0.0, 7.258223095476766e-9])
(u, pdf(D.C, u), pdf.(D.m, x)) = ([0.9999999508852995, 0.0], NaN, [9.82293986661322e-9, 0.0])
(u, pdf(D.C, u), pdf.(D.m, x)) = ([0.0, 0.9999946222242275], NaN, [0.0, 1.075526233505949e-6])
(u, pdf(D.C, u), pdf.(D.m, x)) = ([0.9999927218027077, 0.0], NaN, [1.4556341612406287e-6, 0.0])
(u, pdf(D.C, u), pdf.(D.m, x)) = ([0.0, 0.9999995435907], NaN, [0.0, 9.128165169602381e-8])
(u, pdf(D.C, u), pdf.(D.m, x)) = ([0.9999993823159623, 0.0], NaN, [1.2353676939278703e-7, 0.0])
(u, pdf(D.C, u), pdf.(D.m, x)) = ([0.0, 0.995667252623254], NaN, [0.0, 0.0008474996201505764])
(u, pdf(D.C, u), pdf.(D.m, x)) = ([0.9940233723597347, 0.0], NaN, [0.0011917463827292273, 0.0])
(u, pdf(D.C, u), pdf.(D.m, x)) = ([0.0, 0.9998796290049966], NaN, [0.0, 2.4059704007160166e-5])
(u, pdf(D.C, u), pdf.(D.m, x)) = ([0.999837010733582, 0.0], NaN, [3.2595196589161666e-5, 0.0])
ERROR: DomainError with 0.0:
integrand produced NaN in the interval (-100.0, 100.0)
```

So we can see that the problem comes from the fact that the Gumbel pdf yields nan when a border is zero: 

```julia
pdf(GumbelCopula(2,2.5), [0.1,0.0]) # NaN
pdf(GumbelCopula(2,2.5), [0.0,0.1]) # NaN
pdf(GumbelCopula(2,2.5), [0.0,0.0]) # NaN
```

Let me now try to understand why.

**Comment by rand5** [comment]
@lrnv Thank you for fixing that- I can confirm I'm no longer getting the domain errors that were being thrown before.

I think this has opened the door to another issue though. Take a look at these jumps:
```
X1 = Gumbel(15.,5.)
X2 = MixtureModel([Normal(-6.,0.1),X1],[0.9,0.1])

θ = 2.5
d= 2
C = GumbelCopula(d,θ)

D1 = SklarDist(C,(X1,X2))

N = 1000; zmin = -10.; zmax = 60.
Zs = collect(range(zmin,zmax,N))

ConvD = map(Zs) do z
    quadgk(x->pdf(D1,[x,z-x]), -Inf, Inf)[1]
end

plot(scatter(;x=Zs,y=ConvD))
```
![newplot (25)](https://github.com/user-attachments/assets/5e93da45-99aa-4c86-951c-8bb4efcde1b8)

If the standard deviation of the Normal component of X2 increases, they disappear, and if the standard deviation decreases they increase. Here is with 
```
X2 = MixtureModel([Normal(-6.,0.05),X1],[0.9,0.1])
```
![newplot (26)](https://github.com/user-attachments/assets/10b7c728-8715-4d45-aa98-9d672030d178)

I see similar behavior `X1` is a Gamma distribution instead of a Gumbel. I don't see the issue if `X1` is Normal.

Let me know if you'd like me to migrate this to its own issue.

**Comment by lrnv** [comment]
I guess this is simply integration errors and has nothing more to do with Copulas.jl in particular, right ? 

One "well-converging approximation" would be to decompose your integral and approximate it by monte-carlo on X1. Using your second most-problematix X2, we obtain: 

```julia
using Copulas, Distributions, QuadGK, Plots
X1 = Gumbel(15.,5.)
X2 = MixtureModel([Normal(-6.,0.05),X1],[0.9,0.1])

θ = 2.5
d= 2
C = GumbelCopula(d,θ)

D1 = SklarDist(C,(X1,X2))

N = 1000; zmin = -10.; zmax = 60.
Zs = collect(range(zmin,zmax,N))
ConvD = similar(Zs)

x1 = rand(X1, 10000) # you need enough for monte-carlo to kick in.
u1 = cdf.(X1, x1)
x2, u2 = similar(x1), similar(u1)
for i in eachindex(Zs)
    x2 .= Zs[i] .- x1
    u2 .= cdf(X2, x2)
    p2 = pdf(X2, x2)
    c = pdf(D1.C, hcat(u1,u2)')
    ConvD[i] = mean(c .* p2)
end

plot(Zs, ConvD)
```
![plot_13](https://github.com/user-attachments/assets/5a72935d-89b3-497e-96fb-7cc469af9537)

You might find other more efficient and reliable integration methods, though. 

If you do find something reliable and generic enough, I would be interested to provide the `convolve(D::SklarDist)` function in the package.

**Comment by lrnv** [comment]
My last idea is to swap the mixture and the convolution, as these operations should commute nicely.

**Comment by rand5** [comment]
Looking at the Monte Carlo decomposition you described, it seems like the variability between the two approaches (going from X2->X1 versus X1->X2) comes down to whether we evaluate `p1 = pdf(X1, x1)` or `p2 = pdf(X2, x2)`. The range of p1 is approximately [0, 0.07] while the range of p2 is two orders of magnitude higher at about [0, 7]. So when we go from X1->X2 and are forced to compute `p2`, we are mapping the variability of the Monte Carlo approach onto a much wider interval, which results in a less stable result. 

I agree that the fundamental issue is that the supports are very different from each other and like the idea of taking advantage of the commute, but I'm having trouble translating this into a MWE. Let me know if you have something I can pressure test.

**Comment by lrnv** [comment]
For the commute, you might want to leverage multiple dispatch, since every information you need is in the type of `D1`. Something like that: 

```julia

# Special mixture case: 
function convolve(D::SklarDist{CT, Tuple{T1,T2}}) where {T1 <: Mixture}
	return Mixture(
		convolve(SklarDist(D.C, (D.m[1].components[1],D.m[2]))),
		convolve(SklarDist(D.C, (D.m[1].components[2],D.m[2]))),
		D.m[1].weights # carry on the mixing weights.
    )
end

# Generic version: 
function convolve(D::SklarDist)
	# do the generic stuff.
end
```

But I think this requires defining a subtype of `Distributions.UnivariateDistribution` to hold these convolutions.

**Comment by rand5** [comment]
How about the following for a slightly revised implementation of the generic version:

```
function convolveF(D::SklarDist,Zs::Vector{Float64};N=1000)

    # The primary should be the function with the largest range
    MaxRange = [maximum(x->pdf(X,x),Zs) for X in D.m]
    PrimaryFunID = findmax(MaxRange)[2]
    SecondaryFunID = findmin(MaxRange)[2]

    ConvD = similar(Zs)

    xPrimary = rand(D.m[PrimaryFunID], N)
    uPrimary = cdf.(D.m[PrimaryFunID], xPrimary) 
    xSecondary, uSecondary = similar(xPrimary), similar(uPrimary)

    for i in eachindex(Zs)

        xSecondary .= Zs[i] .- xPrimary
        uSecondary .= cdf(D.m[SecondaryFunID], xSecondary)
        pSecondary = pdf(D.m[SecondaryFunID], xSecondary)

        if PrimaryFunID == 1
            c = pdf(D.C, hcat(uPrimary,uSecondary)')
        else
            c = pdf(D.C, hcat(uSecondary,uPrimary)')
        end
        ConvD[i] = mean(c .* pSecondary)
    end
        
    return ConvD
end
```

Testing it:
```
X1 = Gamma(3.,8.)
X2 = Normal(-6.,0.01)
X3 = Normal(-6.,1.01)
X4 = Normal(-10.,1.01)

θ = 2.5
d= 2
C = GumbelCopula(d,θ)

D1 = SklarDist(C,(X1,X2))
D2 = SklarDist(C,(X1,X3))
D3 = SklarDist(C,(X1,X4))

N = 1000; zmin = -20.; zmax = 80.
Zs = collect(range(zmin,zmax,N))
CD1 = convolveF(D1,Zs)
CD2 = convolveF(D2,Zs)
CD3 = convolveF(D3,Zs)

plot([scatter(;x=Zs,y=CD1),scatter(;x=Zs,y=CD2),scatter(;x=Zs,y=CD3)])
```
![newplot (27)](https://github.com/user-attachments/assets/95aa2be2-d303-43e4-9a50-f00b702947a9)


I'm not that familiar with Copulas, and one thing I don't understand is why `uPrimary = cdf.(D.m[PrimaryFunID], xPrimary)` couldn't be replaced with `uPrimary = rand(Uniform(),N)`. Shouldn't they be equivalent due to the Probability Integral Transform?

**Comment by lrnv** [comment]
Yes they are equivalent, you can definitely replace these two lines with `uPrimary = rand(N)`. 

Furthermore, your code will only work for bivariate SklarDist, and not for d-variates ones for d > 2, so maybe you could restrict to bivariates cases only. Anyway, it looks like on your example this is working quite nicely ? Do you have anything else that you need here ? May i ask you why you ended up on this problem in the first place ?

**Comment by rand5** [comment]
Correct, this is just for bivariates. I was imagining that if there were 3 components (A, B and C), then we could do some sort of nested evaluation  like `convolveF(convolveF(A,B),C)` but I haven't yet thought about the details.

I think the next key item for the bivariate case, which you highlighted, is to take the function evaluations that `convolveF` produces and convert them into univariate distributions that are compatible with `MixtureModel`. I don't have any experience defining custom distributions, but I'm starting to look at how the standard distributions are implemented.

The reason I'm on this topic is I'm trying to model a decision process where you need to assemble a portfolio of "games" that maximizes returns. For each game there are multiple opportunities to trigger small negative returns and an opportunity to trigger a much larger positive return, represented by something like:

Game1:
```
MixtureModel{Distribution{Univariate, Continuous}}(K = 3)
components[1] (prior = 0.3000): Normal{Float64}(μ=-0.2235, σ=0.012)
components[2] (prior = 0.0630): Normal{Float64}(μ=-0.2635, σ=0.0152)
components[3] (prior = 0.6370): Gamma{Float64}(α=7.0, θ=3.0)
```

Game2:
```
MixtureModel{Distribution{Univariate, Continuous}}(K = 5)
components[1] (prior = 0.4600): Normal{Float64}(μ=-0.0335, σ=0.0012)
components[2] (prior = 0.3564): Normal{Float64}(μ=-0.07350000000000001, σ=0.0044)
components[3] (prior = 0.0551): Normal{Float64}(μ=-0.2235, σ=0.0164)
components[4] (prior = 0.0116): Normal{Float64}(μ=-0.2635, σ=0.0196)
components[5] (prior = 0.1170): Gamma{Float64}(α=7.0, θ=3.0)
```

Game3:
```
MixtureModel{Distribution{Univariate, Continuous}}(K = 4)
components[1] (prior = 0.6600): Normal{Float64}(μ=-0.07350000000000001, σ=0.0032)
components[2] (prior = 0.1020): Normal{Float64}(μ=-0.2235, σ=0.0152)
components[3] (prior = 0.0214): Normal{Float64}(μ=-0.2635, σ=0.0184)
components[4] (prior = 0.2166): Gamma{Float64}(α=7.0, θ=3.0)
```

There is some dependence between Game1 and Game2 and between Game1 and Game3, which I'm modeling via copulas. The fundamental question is, is it better to play Game1 and Game2 or Game1 and Game3? The expected total return of playing Game1 and Game2 (or Game1 and Game3) is given by the convolution of those distributions, but, as you can see, in each case the support for the components associated with negative returns in each game is very different from the support for the positive returns, making it difficult to compute the convolutions.

**Comment by lrnv** [comment]
For more than 2 dimensions, you will be able to do nested evaluations like `convolveF(convolveF(A,B),C)` if and only if the dependence structure can be "disasembled", which might not always be the case. 

For the mixtures on the other hand, I think you'll better use the convolution of mixture <=> mixture of convolution. to recusively simplify your problem, by defining a few methods as I proposed in a previous message (if you have trouble doing it, please come back I'd gladly help you). 

Very cool problem indeed ! Do not hesitate to forward the results / publications / output of the project i'd love to read it more in depth.

**Comment by rand5** [comment]
@lrnv Any interest in collaborating on a technical paper?

**Comment by lrnv** [comment]
@rand5 Sure, if I can be of any help

**Comment by rand5** [comment]
With regards to your suggestion to do something like this:
```
function convolve(D::SklarDist{CT, Tuple{T1,T2}}) where {T1 <: Mixture}
	return Mixture(
		convolve(SklarDist(D.C, (D.m[1].components[1],D.m[2]))),
		convolve(SklarDist(D.C, (D.m[1].components[2],D.m[2]))),
		D.m[1].weights # carry on the mixing weights.
    )
end

# Generic version: 
function convolve(D::SklarDist)
	# do the generic stuff.
end
```
Thinking through this-- It boils down to taking one component from the first mixture, then convolving it with one component from the second mixture. The components being convolved are not necessarily the same distribution type, and not necessarily on the [list](https://juliastats.org/Distributions.jl/stable/convolution/) of distributions for which `Distributions.jl` has already implemented the `convolve` function. The reason `Distributions.jl` has implemented the ones they have is because there are nice tidy formulas for the resulting distribution in terms of the parameters of the distributions being convolved.

What I think we are envisioning is definitely harder-- taking any two distributions from `Distributions.jl` and convolving them. Actually, the convolution isn't really the hardest part- its then also finding the CDF, quantile function, and six other [quantities](https://juliastats.org/Distributions.jl/stable/extends/) that need to be defined to make the result compliant with `Distributions.jl` so that it can be fed back into a copula.

One solution would be to have a general pipeline where the input is a pdf specified on some grid of points, then the output is a `Distributions.jl`-compliant distribution. Does something like that already exist? I suspect not since otherwise `Distributions.jl` would already be using it to extend the `convolve` function beyond the special cases.

**Comment by lrnv** [comment]
Even if there are components that might possess a theoretical convolution, these convolutions are usually assuming independence, while here we have dependence structures...

On the other hand providing all the interface of Distributions.jl is not that hard: 
- pdf : we already have it, either through the formal integration or through monte-carlo approximation. 
- cdf : I think the integration formula is very close to the one you had for the pdf
- quantile function: there might be other algorithms relevant here, but in the mean time we can simply inverse the cdf
- rng : well just sample from the original model and sum, that is the easiest one. 
- minimum / maximum / support : easy to deduce from the minimum, maximum, and support of the components. 

So maybe we could provide a structure `DependentConvolution <: Distributions.UnivariateDistribution` that do it. Then the bit of algorithm to simplify mixtures can be implemented as methods to `DependentConvolution`'s constructor.

**Comment by lrnv** [comment]
Also other algorithms exists, e.g. using fourrier transform : https://github.com/bionanoimaging/FourierTools.jl

**Comment by lrnv** [comment]
Hey @rand5 Now (since #194 got merged), we have a way of creating conditional distributions from copulas. This *may* help your convolution issues by using the following identity

$$f_{X_1+X_2}(t) = \int f_{X_1 | X_2 = x_2}(t - x_2)f_{X_2}(x_2) dx_2 \approx \sum_{i=1}^N f_{X_1 | X_2 = x_2}(t - X_{2, i})$$

Now, the conditional distribution is provided directly by the package. So you can simply do: 

```julia
X = SklarDist(ClaytonCopula(2,7), (Normal(),Normal()))
pdf_of_sum(X, t; j=1; N=10000) = mean(pdf(condition(X, j, x2), t - x2) for x2 in rand(X.m[j],N))
```

Depending on the copula (look at the result of `condition(C, j, x2)` to decide, the conditionals might not depend on the value of x2, so it coudl be precomputed to save time. Also you can choose j=1 to condition on the first one, which might work better dependning on the variance of both marginals as we already saw.

**Comment by lrnv** [comment]
Hum .. sorry for ringing you a bit early, these are indeed changes that we plan for 0.1.31, they ar eon master right now. If you want to check out master you can otherwise nevermind I'll ping you again when it's released.

Sorry about that :/

**Comment by lrnv** [comment]
Closing this broad discussion in favor of the focused proposal https://github.com/lrnv/Copulas.jl/issues/407.

The thread established several useful points:

- the Gaussian boundary NaN originated upstream in Distributions.jl and is tracked through the general boundary issue #284;
- the Archimedean boundary/domain errors discussed here were addressed in later Copulas.jl releases;
- discontinuities seen during quadrature were largely numerical-integration concerns rather than a single copula defect;
- conditioning now provides a practical identity for evaluating the PDF or CDF of a sum;
- the previously missing `DistortedDist.logpdf` method is present on current main;
- a reusable feature should be a deliberately scoped univariate `DependentConvolution`, initially for bivariate `SklarDist`, rather than continuing to mix bug reports, integration experiments, mixture simplification and general multivariate convolution in one issue.

Further design work should continue in the new issue.
